### ISSUE TITLE
Reordering in a list on iOS?

### ISSUE THREAD

**Issue by bastiaanterhorst** [Whiffer/swiftdata-transferrable#3]
Hi, I am trying your package and the demo app. On MacOS I can reorder the items in the list, as well as drag items to the two areas at the bottom of the screen. However on iOS I cannot reorder the list. Dragging to the bottom areas works.

Is this a known shortcoming of the library? I'd like to use it to help me reorder across multiple lists, so for me this functionality is crucial.

Also, and purely out of curiosity -- why did you migrate away from using a DropDelegate?

**Comment by bastiaanterhorst** [comment]
Never mind, I did not read. You mention reordering the list does not work. Do you have any clue why this is not working? I need to sort SwiftData across several lists, and can't understand why this is such a pain.

**Comment by Whiffer** [comment]
Hi, for me this functionality is crucial as well.  Earlier this year I was trying very hard to make this work well on macOS, iOS and iPadOS all without having to specialize the solution for each platform.  After spending way too much time trying to make it work, I shifted my priorities and decided to wait for the next WWDC hoping that Apple would provide a solution.  Maybe they did.  I have always thought that SwiftUI's List container View was doing some things "for me" that I didn't necessarily want.  In this case, I suspect that the List View (at least on iOS) may be capturing (and not passing on) the gestures needed for drag and drop to work properly.  I have toyed with the idea of creating a new SwiftUI custom container view to do only 
what I need, but haven't been able to dive into that yet.  

I have attached a Feedback request that I have filed asking to make this work.  Feel free to file another and reference this.
[Feedback FB13648218.pdf](https://github.com/user-attachments/files/16102284/Feedback.FB13648218.pdf)

I don't remember the exact reason for migrating away from DropDelegate, but I suspect that I was  trying to use only the new transferrable API's.

**Comment by Whiffer** [comment]
I forgot to mention that while I was trying to make this work for iOS, I had a dialog with a former Apple engineer who was very familiar with NSPasteboard. Here is some insight he shared:  " I think there is an important difference between macOS and iOS drag and drop bridging: on macOS, the data you want to put on the drag are called in immediately, because they have to be placed up front into an NSPasteboard. On iOS, data loading is deferred until the drop occurs. This saves the drag originator from having to generate representations that no one is interested in."

**Comment by bastiaanterhorst** [comment]
Thanks for your response!
Very interesting. Did you manage to get it to work without List? Like with a LazyVStack for instance? I could consider switching to that.

I also haven’t tried the iOS 18 update yet, but it’s on my list.

**Comment by Whiffer** [comment]
Most of my energy has been focused on macOS lately, but I do need to get back to iOS soon.  I need to try the iOS 18 update as well, along with digging deeper into other possible workarounds.   I’ll create an example project if I do come up with an acceptable solution.

**Comment by Whiffer** [comment]
Bastiaan,  I was able to spend some time with iOS again and it now seems to work, at least for what you wanted. Using the betas of Xcode 16 and an iOS 18.0 simulator I was able to reorder the rows of a List view using drag and drop and simple objects (Strings), but I have still yet to try it using swift data-transferrable objects.  The issue for me is that I would like to be able to reorder rows in a List and also drop a row from the List onto one of the other rows in the same List (e.g. dropping onto a Finder folder). That doesn't seem to work yet with a SwiftUI List view.  I am experimenting with building my own custom List view that will allow both moving rows within the List and dropping rows onto other rows of the same List.

**Comment by bastiaanterhorst** [comment]
Thanks for getting back to me Chuck! I really appreciate that. And very encouraging that it seems to work in iOS 18. 

I’m currently in a crunch to ship something and have been holding off updating to the betas. This is another reason to bite the bullet I guess :)

**Comment by Whiffer** [comment]
FYI, I have updated this package to do more of the required setup inside the package.   In addition, I have modified the companion sample program to demonstrate how it is possible to move rows in a List.  The .onMove() View modifier now seems to work on both iOS and macOS, even on iOS v17.

**Comment by bastiaanterhorst** [comment]
Apologies for not responding sooner -- I was neck deep in something totally unrelated to lists and SwiftData and wanted to keep my focus. I've since been upgrading to the latest SDKs and OSes. It looks like the situation is now opposite from when I initially opened this issue 😭 . Taking your demo app, list sorting works perfectly on iOS with .onMove, but the dropDestination on the main list doesn't seem to work when dragging an item from that same list. Dragging to the other drop areas works as well.

Mac OS is not budging. onMove seems to work, but on any drop action I get:

```
Error loading
net.map-territory.persistentmodelid:
Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type net.map-territory.persistentmodelid" UserInfo={NSLocalizedDescription=Cannot load representation of type net.map-territory.persistentmodelid, NSUnderlyingError=0x600003aa44e0 {Error Domain=NSCocoaErrorDomain Code=3072 "The operation was cancelled."}}

Error loading PersistentIdentifier: The operation couldn’t be completed. (CoreTransferable.TransferableSupportError error 0.)
```

I've played around with different type identifiers, and am going through your code but haven't been able to resolve the issue yet.

**Comment by bastiaanterhorst** [comment]
Seems I was able to fix it!
https://github.com/Whiffer/swiftdata-transferrable/pull/4

**Comment by Whiffer** [comment]
Hi.  Sorry, I'm just getting back into this as well. I finally merged your commits. Thank you.

On iOS, I also see that .onMove works in the same List and .dropDestination does not work onto rows in the same List. However, it does seem to work when dragging a row from one List onto a row in a different List in the same View.  Go figure. I have a feeling that is by design. I'm reworking my UI to use two Lists.

On macOS, I am getting the same "Error Loading" that you observed.  Your last comment said you were able to fix it, but I am still getting the error when compiling and running on Sequoia.  Are you getting successful drops anywhere with .dropDestination on macOS?  Did I miss something?  Thanks.

**Comment by Whiffer** [comment]
FYI, I finally was able to isolate the reason for the "Error Loading" issue on macOS.  The culprit is the .onMove() modifier.  It does not work as expected on macOS and only should be compiled for iOS targets.  I updated my sample program with conditional compiles and it is now able to reorder List View rows on both platforms.  However, you will still have to supply separate code to do the actual reordering on each platform.

**Comment by bastiaanterhorst** [comment]
That's interesting! I'm still stumped why this is so complicated and not as easy as the docs make it out to be. In the end I went with my own solution based off oldschool onDrop and onDrag. I've also ditched List for a homegrown solution because it was just too much swimming upstream to make List do what I needed.
